kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: manipulate-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: manipulation-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: External
      external:
        metric:
          name: manipulate_average_requests
          selector:
            matchLabels: 
              k8s.namespaceName: default
        target:
          type: Value 
          value: 100